# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Blog
email: msh907@kookmin.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  This is Min Seung-ho's Eureka Project Class Blog of Software Department 20212991.
  This is a blog to upload what was covered in this special lecture on the use of GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site http://yourdomain.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
comment:
  provider:          "disqus"
  disqus:
    shortname:       "seungho-eureka.disqus.com"